### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by elbogi** [ptz0n/homebridge-verisure#1]
Hei.

The plugin installs just fine, but I get the following error starting Homebridge:

_====================
ERROR LOADING PLUGIN homebridge-verisure:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.load (C:\Users\***\AppData\Roaming\npm\node_modules\homebridge\lib\plugin.js:65:22)
    at Server.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:132:14)
    at Array.forEach (native)
====================_

I run Homebridge on Windows 10, and trying to run Homebridge in strict mode (`node --use_strict homebridge` does not work either. Is this a Windows related issue you think?

**Comment by ptz0n** [comment]
Did you get around this issue? I should fix this anyway..

**Comment by elbogi** [comment]
Yes, got around it by ditching win10 as a platform and using av Linux VM instead. But now I'm moving Homebridge over to a macOS to be able to use AppleScript :)

**Comment by christophedelanghe** [comment]
I have the same issue on a Raspberry Pi
