### ISSUE TITLE
Problem with the new token system

### ISSUE THREAD

**Issue by ZEEN0j** [ptz0n/homebridge-verisure#114]
I’ve followed the instructions but I can’t get it to work. I’m running this using hoobs and the service won’t start. This is what I see in the logs

```bash
2021-03-18 20:52:59 (node:1306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-03-18 20:53:19 Initializing HAP-NodeJS v0.9.3...
2021-03-18 20:53:20 Loaded plugin 'homebridge-verisure'
2021-03-18 20:53:20 [3/18/2021, 20:53:20] Registering platform 'homebridge-verisure.verisure'
2021-03-18 20:53:20 Loading 1 platforms...
2021-03-18 20:53:20 [verisure] Initializing verisure platform...
2021-03-18 20:53:21 (node:1343) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
2021-03-18 20:53:21 at createError (/home/hoobs/.hoobs/node_modules/axios/lib/core/createError.js:16:15)
2021-03-18 20:53:21 at settle (/home/hoobs/.hoobs/node_modules/axios/lib/core/settle.js:17:12)
2021-03-18 20:53:21 at IncomingMessage.handleStreamEnd (/home/hoobs/.hoobs/node_modules/axios/lib/adapters/http.js:260:11)
2021-03-18 20:53:21 at IncomingMessage.emit (events.js:215:7)
2021-03-18 20:53:21 at endReadableNT (_stream_readable.js:1184:12)
2021-03-18 20:53:21 at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-18 20:53:21 (node:1343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2021-03-18 20:53:21 (node:1343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ptz0n** [comment]
Hi & thanks for reaching out. As your log states, authentication failed (HTTP 401).

- Did you run `npx verisure` and got the config params? You need to paste `email` and `token` into HOOBS.
- Double check that you didn't miss or add any characters, like `"`.

**Comment by ZEEN0j** [comment]
Hi,

I did run the npx verisure but it didn’t save the token in the config by itself when I use the terminal in Hoobs. Could that be the issue? What I did was add the token line manually in the config after running it in the terminal. I don’t think the issue is missing characters as Hoobs warns you. I also temporarily disabled verisure 2FA and input my password instead and that worked.

**Comment by ptz0n** [comment]
To clarify, `npx verisure` does not update your config. You always need to manually copy and paste the values into your config.

Please try again 👍
