### ISSUE TITLE
Can't login with npx verisure

### ISSUE THREAD

**Issue by joaodforce** [ptz0n/homebridge-verisure#122]
Hello there, I'm trying out the plugin, however I tried login in with the `npx verisure` command, but I'm getting a 401 error.

One information i have, is that I don't login with an Email on the `New My Verisure` app. I have an username and password.

I'm also from Brazil. I don't know if maybe there is a need to log into another domain perhaps?

```
(node:5551) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:5551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5551) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ptz0n** [comment]
Verisure Brazil (https://www.verisure.com.br) is actually Securitas Direct. You should try this plugin instead: [homebridge-securitas-direct](https://github.com/ptz0n/homebridge-securitas-direct)
