### ISSUE TITLE
Verisure broke token generation

### ISSUE THREAD

**Issue by C-HGP** [ptz0n/homebridge-verisure#127]
Hi!

Today I got this after the verisure webpage was down. Could it be something changed?
I can't seem to get it working again.

```
[07/10/2021, 21:44:18] [verisure] Initializing verisure platform...
(node:2461) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /usr/local/lib/node_modules/homebridge-verisure/lib/platform.js:101:42
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2461) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2461) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by C-HGP** [comment]
> The error message could be better. Did you try restarting the service?

Yes, i've restarted everything, i've tried reinstalling the plugin several times, even having a config without any data and the error pops up on boot of the plugin. I've tried reinstalling homebridge and different versions of homebridge aswell as this plugin. I have also tried reinstalling a fresh copy of rasbian to the pi and then installing homebridge via npm to be sure that it wasnt a distro error. Still get the exact same problem. 

That is sadly the only error message I get.

**Comment by Lanjelin** [comment]
Been trying since yesterday evening to get this working.
Fresh install, never tried the plugin before.

With and without MFA.
Installed both from Homebridge plugins, and from shell.
Docker (don't see it should matter).
Norway.

Guess Verisure has done something, as it throws 403?

Logs generally throw out the following:

```
[10/8/2021, 7:28:00 AM] [zigbee2mqtt] Using Zigbee2MQTT v1.21.2 (identified via zigbee2mqtt/bridge/info)
(node:2487) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/8/2021, 7:28:19 AM] [homebridge-verisure] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
wakeUntilAPIReady: try 10
```

Running ```npx verisure``` lets me put in username and password, then spits out
```
(node:2716) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ptz0n** [comment]
Okej, I'm not using Homey but I do use MFA. No issues with my setup. Let's focus on getting MFA working.

**Comment by utezduyar** [comment]
I have also started getting 403 errors. Things stopped working this morning. The plugin doesn't load and the entire homebridge is not starting. 

I do not have MFA, I have a dedicated user for homebridge without MFA.

**Comment by utezduyar** [comment]
```
(node:568) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by C-HGP** [comment]
> > As I said, Verisure HAS rolled out a patch to the web and application because of an error where users who had Homey got spammed via SMS. I am positive that this is a probable cause of this error.
> 
> Checked on my Homey, and the Verisure app is suddenly not working (it did some time earlier this week, I know for sure). Haven't gotten any SMS though.

I think the Homey-Verisure plugin rolled out a patch yesterday after this change, so if you update your Homey-verisure plugin, it should work. I am, however dependent on homebridge as I don't have a Homey.

**Comment by utezduyar** [comment]
Thank you! It worked great.
