### ISSUE TITLE
/usr/local/lib/node_modules/homebridge-verisure/index.js:59

### ISSUE THREAD

**Issue by askusbloodfist** [ptz0n/homebridge-verisure#14]
Hi from what i seen before someone posted a problem must like this. But it was closed without any explination to if you solved it or what realy happend. 

My RP is all updated but has Node-Js 4.8.
Latest Homebridge And i get what you se when trying to run your plugin. 
Other then this problem my Enviroment works flawless with Light dims and other things using my telldus. 

```bash
[7/6/2017, 4:31:02 AM] Loaded plugin: homebridge-telldus
[7/6/2017, 4:31:02 AM] Registering platform 'homebridge-telldus.Telldus'
[7/6/2017, 4:31:02 AM] ---
[7/6/2017, 4:31:03 AM] Loaded plugin: homebridge-verisure
[7/6/2017, 4:31:03 AM] Registering platform 'homebridge-verisure.verisure'
[7/6/2017, 4:31:03 AM] ---
[7/6/2017, 4:31:03 AM] Loaded config.json with 0 accessories and 2 platforms.
[7/6/2017, 4:31:03 AM] ---
[7/6/2017, 4:31:03 AM] Loading 2 platforms...
[7/6/2017, 4:31:03 AM] [Verisure] Initializing verisure platform...
[7/6/2017, 4:31:03 AM] [Telldus Liv!e] Initializing Telldus platform...
[7/6/2017, 4:31:03 AM] [Telldus Liv!e] Loading accessories...
[7/6/2017, 4:31:03 AM] Loading 0 accessories...
Load homebridge-verisure.verisure
[7/6/2017, 4:31:03 AM] [Telldus Liv!e] Logged in with user: jimmyhawkin@gmail.com
[7/6/2017, 4:31:03 AM] [Telldus Liv!e] Found 0 sensors in telldus live.
[7/6/2017, 4:31:03 AM] [Telldus Liv!e] Found 13 devices in telldus live.
/usr/local/lib/node_modules/homebridge-verisure/index.js:59
  if(VERISURE_DEVICE_NAMES.includes(name)) {
                           ^

TypeError: VERISURE_DEVICE_NAMES.includes is not a function
    at getUniqueName (/usr/local/lib/node_modules/homebridge-verisure/index.js:59:28)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:95:19
    at Array.map (native)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:92:46
    at /usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:79:7
    at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:27:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by askusbloodfist** [comment]
{
	"bridge": {
		"name": "xxxxxxxxxxxxx",
		"username": "xxxxxxxxxxxxxxxxxxxxxx",
		"port": xxxxxxxxxxxxxx,
		"pin": "xxxxxxxxxxxxxxxxx"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [],

	"platforms": [{
			"platform": "verisure",
			"name": "Verisure",
			"email": "xxxxxxxxxxxxxxxxxxxxxx",
			"password": "xxxxxxxxxxxxxxxxxxxxxx"
				},
				{
			"platform": "Telldus",
			"name": "Telldus Liv!e",
			"public_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"private_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"token_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"unknown_accessories": [{
					"id": 1554085,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554089,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554113,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554140,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554049,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554060,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 123,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1602418,
					"model": "selflearning-dimmer",
					"manufacturer": "Nexa"
				},
				{
					"id": 1603882,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1603887,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1666884,
					"model": "selflearning-switch",
					"manufacturer": "Cotech"
				},
				{
					"id": 456,
					"model": "temperaturehumidity",
					"manufacturer": "Oregon",
					"name": "My Custom Name"
				},
				{
					"id": 789,
					"name": "Only name altered"
				},
				{
					"id": 987,
					"disabled": true
				},
				{
				}
			]
		}
	]
}

**Comment by askusbloodfist** [comment]
For people that might run in to this problem sins most people will come from 4.0 Node-js and NPM versions lower then 3.0. I succesfully got this working with Node-JS v8.1.3 And NPM 5.1.0 And with a Config looking as above. 

Comming from a Homebridge with node 4.0 that means basicly starting over. And update to NodeJS 8.1.3 first then update the NPM. Then Install Homebridge and then all plugins. Then everything works perfekt.

**Comment by kodsnutten** [comment]
Good catch @askusbloodfist ! 
I previously noted that this plugin uses the "verisure"-plugin, which also has a dependency on a newer Node-js version than stated in the package.json...

I think that the "verisure" plugin requires Node-js v 5.10 because of the [Buffer-class](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding).

According to [this V8-issue](https://github.com/tc39/Array.prototype.includes/issues/7) the `Array.includes`-function was added in V8 version 4.7, and the V8 engine was upgraded in Node-js 6.0.0 (according to [this release table](https://nodejs.org/en/download/releases/)), so I assume that this plugin **requires at least Node-js 6.0.0**

**Comment by ptz0n** [comment]
As @kodsnutten clarified perfectly, this plugin requires `"node": ">=6"`. This have been reflected in the `dev` branch which will hopefully be merged soon.
