### ISSUE TITLE
Unable to find my token !

### ISSUE THREAD

**Issue by Madcat-76310** [ptz0n/homebridge-verisure#147]
Hi everybody, i can't find my token using npx, i get this error :

(node:5478) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/pi/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by Madcat-76310** [comment]
I use securitas direct, in France (it's the same than GB, Spain, etc.).
Some ideas  to help me ?

**Comment by ptz0n** [comment]
Oh, yes. That's the issue; you should not use this plugin but rather https://github.com/ptz0n/homebridge-securitas-direct

As stated in the README, this plugin only supports Vbox installations.

**Comment by Madcat-76310** [comment]
Hi, ok, i'll try again the other plugin (last time it's not run). Thank you !
