### ISSUE TITLE
⭐️ Verisure deprecated REST API: Error at startup

### ISSUE THREAD

**Issue by Stianker1** [ptz0n/homebridge-verisure#150]
**Summary of the problem;** Verisure have changed the hostnames to their API.

---

I noticed that i have trouble with getting the verisure child bridge up and running. it loops the error message you can see down below. i tried to start it without child bridge, but that just looped homebridge in to a restart.
it worked fine yesterday.

```bash
[15/03/2023, 09:55:35] [homebridge-verisure] Restarting Process...
[15/03/2023, 09:55:35] [Ebeco] Sensor config: floor
[15/03/2023, 09:55:36] [homebridge-verisure] Launched child bridge with PID 17299
[15/03/2023, 09:55:36] Registering platform 'homebridge-verisure.verisure'
[15/03/2023, 09:55:36] [homebridge-verisure] Loaded homebridge-verisure v1.16.0 child bridge successfully
[15/03/2023, 09:55:36] Loaded 0 cached accessories from cachedAccessories.0E96B5C2DDC6.

/var/lib/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 404
    at createError (/var/lib/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[15/03/2023, 09:55:36] [homebridge-verisure] Child bridge process ended
[15/03/2023, 09:55:36] [homebridge-verisure] Process Ended. Code: 1, Signal: null
```

**Comment by helangen** [comment]
I have the same error since yesterday. Maybe Verisure updated something.
Running HB v1.6.0, Node.js 18.15, Verisure 1.16 as a child bridge

**Comment by helangen** [comment]
Will you update the plugin, or do we have to do something on our side?

**Comment by ptz0n** [comment]
I’m updating the plugin, but don’t have time right now. Please submit a PR and I’ll be happy to review and merge it 👍🏼

**Comment by mikaelisaxon** [comment]
Same issue here. Any ETA?

**Comment by ptz0n** [comment]
Contributions are most welcome, either in form of code or https://www.paypal.com/paypalme/ptz0n - to help prioritise ♥️

**Comment by barthoefs** [comment]
Same issue here :(

**Comment by Dababa26** [comment]
Pareil aussi… problème depuis ce matin!!! Une solution en vue? Merci

**Comment by ZEEN0j** [comment]
> Contributions are most welcome, either in form of code or https://www.paypal.com/paypalme/ptz0n - to help prioritise ♥️

Sent a small contribution. Please fix this

**Comment by helangen** [comment]
Sent a small contribution also. Thanks for your work.

**Comment by digidolphin** [comment]
Sent a contribution. I hope you can fix it.

**Comment by ZEEN0j** [comment]
Any sort of ETA?

**Comment by ptz0n** [comment]
Contributions recieved ❤️ I have working auth and calls to the new GraphQL endpoint.

**Comment by mwouda** [comment]
i'm getting the same error: For now i disabled the plugin until you have a fix. Thx for great work

_3/17/2023, 10:48:01 AM] Error: Request failed with status code 404
    at createError (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-verisure/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[3/17/2023, 10:48:01 AM] Got SIGTERM, shutting down Homebridge...
[3/17/2023, 10:48:01 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)_

**Comment by Dababa26** [comment]
Comment évolue le travail? Une mise à jour est prévue? Bien à vous

**Comment by d3linma** [comment]
Thanks for you work and a great plug-in! I also donated, would very much like a fix for this bug

**Comment by ptz0n** [comment]
**Progress update;** the client module `v5.0.0` is now released with support for new auth and GraphQL. Good night all!

![dance](https://user-images.githubusercontent.com/200250/226070806-00211a0b-e257-461c-a703-8be0c1d87144.gif)

**Comment by ZEEN0j** [comment]
Will you be pushing an update for the plug in that needs to be installed?

**Comment by ptz0n** [comment]
@ZEEN0j Yes, the plugin needs to be updated once the new version is released.

**Comment by ZEEN0j** [comment]
Awesome. Very much appreciated

**Comment by helangen** [comment]
Thanks for your hard work

**Comment by torandreroland** [comment]
Thank you for your hard work on updating node-verisure, @ptz0n! Looking forward to the subsequent update of this plugin as well.

**Comment by chave** [comment]
I saw my system stop reacting to my automation, check the error and go here. What an incredible community and thank you for your hard work.

**Comment by ptz0n** [comment]
**Update, done so far:**

- Platform (initiating) to request accessories and their states using new interface.
- Working security system (alarm) accessory.

---

It's truly heartwarming to see all your contributions. I created this plugin for my own use and would not have imagined the amount of installations, support with ideas, bug reports, code and donations.

_You guys are awesome!_

**Comment by ptz0n** [comment]
Are you ready? Teaser:

<img width="901" alt="Screen Shot 2023-03-19 at 10 58 14" src="https://user-images.githubusercontent.com/200250/226168003-db0f16d9-fe68-4226-a831-496613eeede6.png">

Door lock accessory is the last one. Might need some help because I don't have that device type in my installation.

**Comment by ZEEN0j** [comment]
I have a yale doorman lock with Verisure module. What do you need?

**Comment by helangen** [comment]
Me too. Let me know if we assist.

**Comment by ptz0n** [comment]
**Ready for testing.** Please help out and report any issues directly in #152. Focus on door lock accessories as I'm not able to test these in my installation. Lock, unlock, enable/disable auto lock and change volume.

**Update the plugin globally**

```bash
$ npm install -g git://github.com/ptz0n/homebridge-verisure#graphql
```

**… or run it from a working dir**

```bash
$ git clone https://github.com/ptz0n/homebridge-verisure.git
$ cd homebridge-verisure
$ git checkout graphql
$ npm install
$ npm start
```

**Comment by Stianker1** [comment]
I tried both things and it still ends up like before. I dont know if im doing something wrong! Thank you for your hard work 😊

**Comment by ZEEN0j** [comment]
Haven’t been able to install it yet (probably an issue on my end). I’m running hoobs and I’m in the terminal trying the update globally command but it says it came find the command

**Comment by bjornand1** [comment]
Million thanks for working on this!

I am now able to avoid having the plugin crash Homebridge, but none of the devices show up under accessories. And when I restart Homebridge, Verisure sends me a one-time code via SMS, which seems a bit strange.

I have followed the instructions in Readme, obtained the token using npx homebridge-verisure.

In the log, I get this (red) line:

[3/19/2023, 5:14:07 PM] [Verisure] MFA is enabled for user. Please see README.

**Comment by Cm0ller** [comment]
Same problem as @bjornand1 here. Thanks for the updates!

**Comment by torandreroland** [comment]
Thanks for providing this test version and again for your hard and excellent work!

I have this working (in my setup I have a smart plug, three contact sensors, a security system, a siren and various smoke detectors) except for the switch-services for auto-lock and audio level. Both of them are unresponsive and I think there is a problem with getting the state of one of the characteristics.

Also, I struggled a bit with the two-factor authentication. But I got the correct cookies after rerunning the cli-tool verisure in /bin. It may be good to clarify how to actual get the various cookies (since the prior version only required one token) when migrating to the graphql-api, including updating remnant mentions of token in the README.

Lastly, I also struggled with getting the updated version installed in my docker environment (somehow it would only install to the npm cache, which was easy enough to move once I understood where it got installed). It would be a lot easier to install this test-version if you pushed it as a beta version to NPM, as it would be available using the "install alternate version"-functionality in homebridge-config-ui-x

**Comment by ptz0n** [comment]
Indeed. You need to run:

```bash
$ ./path/to/homebridge-verisure/bin/verisure
```

This will eventually output a list of `cookies` to put in your config, instead of `token` like before.

**Comment by ptz0n** [comment]
@bjornand1 You need a property called `cookies` in your config. `token` is deprecated. Please see my comment above.

**Comment by bjornand1** [comment]
Hmm, still not really getting there. In Terminal, I have navigated to the verisure folder in bin, but which command do I run there to get the cookes?

**Comment by helangen** [comment]
> Hmm, still not really getting there. In Terminal, I have navigated to the verisure folder in bin, but which command do I run there to get the cookes?

./verisure

**Comment by helangen** [comment]
Just updated and got cookies. Testing now. Will send feedback

**Comment by bjornand1** [comment]
Thanks, @helangen, but I just get no such file or directory

**Comment by helangen** [comment]
So I get this from the log. Now locks or alarms showing, only sensors.

[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Stue): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Stue): Getting current humidity value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Master bedroom): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Master bedroom): Getting current humidity value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme SIREN (Kjøkken): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Hall): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Hall): Getting current humidity value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Hall 2 etg): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Hall 2 etg): Getting current humidity value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme VoiceBox (Hall): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Kjeller): Getting current temperature value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme Smoke detector (Kjeller): Getting current humidity value.
[3/19/2023, 7:08:02 PM] [Verisure] Hjemme HOMEPAD (Hall 2 etg): Getting current temperature value.

**Comment by helangen** [comment]
> Thanks, @helangen, but I just get no such file or directory

What's the output of the directory your in? My install is here:

/var/lib/homebridge/node_modules/homebridge-verisure/bin

So you either run ./verisure if you are in this directory or you can run

/var/lib/homebridge/node_modules/homebridge-verisure/bin/verisure

from any directory.

**Comment by bjornand1** [comment]
Getting it now!

**Comment by helangen** [comment]
I just saw that the RC v2.0 was pushed. Trying to install that now

**Comment by ptz0n** [comment]
**FYI:** `2.0.0-rc.0` don't have any updates other than README. Wanted to make it easier to install via Config UI, as mentioned above.

Hopefully have a fix for getting and setting door lock configuration later tonight.

**Comment by helangen** [comment]
> **FYI:** `2.0.0-rc.0` don't have any updates other than README. Wanted to make it easier to install via Config UI, as mentioned above.
> 
> Hopefully have a fix for getting and setting door lock configuration later tonight.

And the alarm state I assume? I don't have that either, but saw that @torandreroland had it. I have two of the same V2N locks.

**Comment by bjornand1** [comment]
Hmm, now the command runs, but I still get a token, not a cookie...

**Comment by helangen** [comment]
> Hmm, now the command runs, but I still get a token, not a cookie...

You should get a whole configuration

✔ What is your one-time code? · xxxxxx

 Your config is ready. 

{
  "platform": "verisure",
  "name": "Verisure",
  "email": "*redacted*",
  "cookies": [
    "vid=*redacted*",
 "vsaccess=*redacted*",
    "vs-refresh=*redacted*"
  ]

**Comment by bjornand1** [comment]
@helangen I fear I might be running the command in the wrong place, i.e., for the old plugin?

**Comment by helangen** [comment]
> @helangen I fear I might be running the command in the wrong place, i.e., for the old plugin?

Seems that way. Just install the v2.0 RC candidate then from the UI. Might be easier. Then you should only have one plugin dir

**Comment by bjornand1** [comment]
@helangen Thanks for trying to help a Terminal idiot like me!

I have updated the plugin, and if I use the Terminal window in HB UI, I can cd my way to the bin, but I still get a token and not a cookie

**Comment by Stianker1** [comment]
I am impressed. You got it up and running before the home assistant guys did 😅 that has to mean something 🙌🏼 thank you so much for solving this issue.

**Comment by ptz0n** [comment]
Thanks a lot! I'm keeping this open until the new version is released.

**Comment by helangen** [comment]
> @helangen Thanks for trying to help a Terminal idiot like me!
> 
> I have updated the plugin, and if I use the Terminal window in HB UI, I can cd my way to the bin, but I still get a token and not a cookie

No worries. What is the path?

**Comment by helangen** [comment]
> > @helangen Thanks for trying to help a Terminal idiot like me!
> > I have updated the plugin, and if I use the Terminal window in HB UI, I can cd my way to the bin, but I still get a token and not a cookie
> 
> No worries. What is the path? And can you give us the output? (redact the sensitive information). Check also if the date of the files in the "homebride-verisure" dir has been updated. You can use e.g. "ls -la" to check.

**Comment by bjornand1** [comment]
@helangen The path is /var/packages/homebridge/shares/homebridge/node_modules/homebridge-verisure

The output is what I would expect, except there is a token instead of a cookie.

**Comment by helangen** [comment]
> @helangen The path is /var/packages/homebridge/shares/homebridge/node_modules/homebridge-verisure
> 
> The output is what I would expect, except there is a token instead of a cookie.

OK. The dates should reflect that you updated today. Do you have an old Homebridge install by chance? What system are you on?

**Comment by helangen** [comment]
> I am impressed. You got it up and running before the home assistant guys did 😅 that has to mean something 🙌🏼 thank you so much for solving this issue.

Second this. Good work and much appreciated.

**Comment by DieterC1984** [comment]
Updated the plug-in in homebridge and everything is running rock solid again. Thanks a million!

**Comment by bjornand1** [comment]
@helangen Thanks again, checked the dates and they are from March 2022. I even uninstalled the plugin and reinstalled, but they remain the old ones. I am running Homebridge on a Synology (not in Docker).

Calling it quits for tonight, though

**Comment by helangen** [comment]
> @helangen Thanks again, checked the dates and they are from March 2022. I even uninstalled the plugin and reinstalled, but they remain the old ones. I am running Homebridge on a Synology (not in Docker).
> 
> Calling it quits for tonight, though

Then it seems like the plugin is not installing correctly. Maybe do a backup and re-install homebridge.

**Comment by chave** [comment]
I run npx homebridge-verisure and follow the process.
I update the config and replace my old token etc with a cookie. 
I restart the homebridge with the new config.
Get this error: 
`[verisure] Unable to get installations. Please check configured credentials: Request failed with status code 401`

**Comment by helangen** [comment]
> I run npx homebridge-verisure and follow the process. I update the config and replace my old token etc with a cookie. I restart the homebridge with the new config.
> 
> It complained about a 401 error for a while, but after a couple of restarts it came online. Happy camper. Thanks for your hard work over the weekend!!

Did you install the RC1 or 3 candidate? The RC2 had this issue.

**Comment by chave** [comment]
> > I run npx homebridge-verisure and follow the process. I update the config and replace my old token etc with a cookie. I restart the homebridge with the new config.
> > It complained about a 401 error for a while, but after a couple of restarts it came online. Happy camper. Thanks for your hard work over the weekend!!
> 
> Did you install the RC1 or 3 candidate? The RC2 had this issue.

It right now tells me RC4 is available. After upgrading, it has zero complaints. Maybe that was it. It feels solid now :)

**Comment by helangen** [comment]
> > > I run npx homebridge-verisure and follow the process. I update the config and replace my old token etc with a cookie. I restart the homebridge with the new config.
> > > It complained about a 401 error for a while, but after a couple of restarts it came online. Happy camper. Thanks for your hard work over the weekend!!
> > 
> > 
> > Did you install the RC1 or 3 candidate? The RC2 had this issue.
> 
> It right now tells me RC4 is available. After upgrading, it has zero complaints. Maybe that was it. It feels solid now :)

The issues are with the Yale Doorman locks. If you don't have these, then you would be fine with v2.0.0

**Comment by chave** [comment]
> > > > I run npx homebridge-verisure and follow the process. I update the config and replace my old token etc with a cookie. I restart the homebridge with the new config.
> > > > It complained about a 401 error for a while, but after a couple of restarts it came online. Happy camper. Thanks for your hard work over the weekend!!
> > > 
> > > 
> > > Did you install the RC1 or 3 candidate? The RC2 had this issue.
> > 
> > 
> > It right now tells me RC4 is available. After upgrading, it has zero complaints. Maybe that was it. It feels solid now :)
> 
> The issues are with the Yale Doorman locks. If you don't have these, then you would be fine with v2.0.0

It's not complaining now and I have all my accessories available and controllable. Thanks!

**Comment by helangen** [comment]
> > > > > I run npx homebridge-verisure and follow the process. I update the config and replace my old token etc with a cookie. I restart the homebridge with the new config.
> > > > > It complained about a 401 error for a while, but after a couple of restarts it came online. Happy camper. Thanks for your hard work over the weekend!!
> > > > 
> > > > 
> > > > Did you install the RC1 or 3 candidate? The RC2 had this issue.
> > > 
> > > 
> > > It right now tells me RC4 is available. After upgrading, it has zero complaints. Maybe that was it. It feels solid now :)
> > 
> > 
> > The issues are with the Yale Doorman locks. If you don't have these, then you would be fine with v2.0.0
> 
> It's not complaining now and I have all my accessories available and controllable. Thanks!

It is still an issue with the Volume Switch in RC4 though. Everything else seems to work fine.

**Comment by torandreroland** [comment]
Volume switch works fine on my end with RC4.

**Comment by ZEEN0j** [comment]
Got it installed and working. Many many thanks. I have a question. If I change my password or enable/disable 2fa on my Verisure account. Will this affect the setup where you would then need to update the cookie in the config?

**Comment by bjornand1** [comment]
All you guys who understand this far better then me, I hope you can help me, because I am stumped.

My problem is that I just cannot find the folder where the verisure plugin gets installed. Some facts/history:

* I have Homebridge installed on a Synology DMS, as a package, not in Docker
* This has worked very well for a long time, but recently when trying to update a plugin, using the graphical UI, I got an error message that I didn’t have the user access rights required
* I therefore followed the advice provided at the GitHub page for the Config UI X:
    * # cleanup
    * sudo npm uninstall -g homebridge-config-ui-x
    * 
    * # reinstall
    * sudo npm install -g --unsafe-perm homebridge-config-ui-x
* After that, I can again install/update plugins without any such errors, but now plugin folders are split between two (three) locations:
    * Those installed before I did this cleanup are under /var/packages/homebridge/shares/homebridge/node_modules
    * New ones installed after this cleanup can go to two locations:
        * Using the Config UI, I have no idea where it ends up, searching in File Station in DSM finds no folder or file with Verisure in the name
        * Using Terminal, they are under /usr/local/lib/node_modules
* However, when using Terminal on my Mac to ssh into the Synology DSM, when I navigate to this latter folder with the plugins, I get the message “-sh: cd: homebridge-verisure: Permission denied”
* Thus, I am not able to run the ./Verisure command to obtain the cookie

This has me stuck and I just can’t get the Verisure plugin to work again, and I hope someone can shed some light on this?

**Comment by helangen** [comment]
> Got it installed and working. Many many thanks. I have a question. If I change my password or enable/disable 2fa on my Verisure account. Will this affect the setup where you would then need to update the cookie in the config?

It was like this when using tokens, so probably yes.

**Comment by helangen** [comment]
> All you guys who understand this far better then me, I hope you can help me, because I am stumped.
> 
> My problem is that I just cannot find the folder where the verisure plugin gets installed. Some facts/history:
> 
> * I have Homebridge installed on a Synology DMS, as a package, not in Docker
> * This has worked very well for a long time, but recently when trying to update a plugin, using the graphical UI, I got an error message that I didn’t have the user access rights required
> * I therefore followed the advice provided at the GitHub page for the Config UI X:
>   
>   * # cleanup
>   * sudo npm uninstall -g homebridge-config-ui-x
>   
>   * # reinstall
>   * sudo npm install -g --unsafe-perm homebridge-config-ui-x
> * After that, I can again install/update plugins without any such errors, but now plugin folders are split between two (three) locations:
>   
>   * Those installed before I did this cleanup are under /var/packages/homebridge/shares/homebridge/node_modules
>   * New ones installed after this cleanup can go to two locations:
>     
>     * Using the Config UI, I have no idea where it ends up, searching in File Station in DSM finds no folder or file with Verisure in the name
>     * Using Terminal, they are under /usr/local/lib/node_modules
> * However, when using Terminal on my Mac to ssh into the Synology DSM, when I navigate to this latter folder with the plugins, I get the message “-sh: cd: homebridge-verisure: Permission denied”
> * Thus, I am not able to run the ./Verisure command to obtain the cookie
> 
> This has me stuck and I just can’t get the Verisure plugin to work again, and I hope someone can shed some light on this?

Check the permissions and the user on the folder. And which user are you login as?

**Comment by bjornand1** [comment]
@helangen Thanks, I ran a permission check, with the following result:

bjorna@SynologyDS720:/usr/local/lib/node_modules$ ls -l
total 16
drwx------ 5 root root 4096 Mar 15 12:23 homebridge-config-ui-x
drwx------ 4 root root 4096 Mar 15 11:28 homebridge-synology
drwx------ 5 root root 4096 Mar 20 07:10 homebridge-verisure
lrwxrwxrwx 1 root root   63 Mar  8  2022 npm -> /var/packages/Node.js_v12/target/usr/local/lib/node_modules/npm

I am running Terminal with the main DSM admin user.

**Comment by helangen** [comment]
> @helangen Thanks, I ran a permission check, with the following result:
> 
> bjorna@SynologyDS720:/usr/local/lib/node_modules$ ls -l total 16 drwx------ 5 root root 4096 Mar 15 12:23 homebridge-config-ui-x drwx------ 4 root root 4096 Mar 15 11:28 homebridge-synology drwx------ 5 root root 4096 Mar 20 07:10 homebridge-verisure lrwxrwxrwx 1 root root 63 Mar 8 2022 npm -> /var/packages/Node.js_v12/target/usr/local/lib/node_modules/npm
> 
> I am running Terminal with the main DSM admin user.

So if you are user "admin" and look at the permissions only root has access. You have to run with "sudo".

**Comment by bjornand1** [comment]
I tried enabling the admin (system default user) and logging in with that in Terminal, but with same result:

admin@SynologyDS720:/usr/local/lib/node_modules$ cd homebridge-verisure
-sh: cd: homebridge-verisure: Permission denied

I can't understand which user has access to this folder?

**Comment by helangen** [comment]
> I tried using sudo in front of the cd command to navigate into these folders, but get this:
> 
> bjorna@SynologyDS720:/usr/local/lib/node_modules$ sudo cd homebridge-verisure Password: sudo: cd: command not found

That doesn't work. You have to run the command in the ../homebridge-verisure folder with sudo. Like this

`sudo /usr/local/lib/node_modules/homebridge-verisure/verisure`

**Comment by helangen** [comment]
> I tried enabling the admin (system default user) and logging in with that in Terminal, but with same result:
> 
> admin@SynologyDS720:/usr/local/lib/node_modules$ cd homebridge-verisure -sh: cd: homebridge-verisure: Permission denied
> 
> I can't understand which user has access to this folder?

Only 'root' has access according to your permissions. Both user 'root' and group 'root' owns the files/folders and only the user 'root' has read, write and execute access.

**Comment by bjornand1** [comment]
Finally, I didn't realize I had to run the command "sudo -i" first in Terminal - now it works!!!

**Comment by bjornand1** [comment]
But no door lock...

**Comment by helangen** [comment]
> But no door lock...

Check your configuration. You might be missing something there.

**Comment by bjornand1** [comment]
Good tip, but what is required to active the Yaleman lock? All other items seem to load

**Comment by ZEEN0j** [comment]
> Good tip, but what is required to active the Yaleman lock? All other items seem to load

If you haven’t already you need to add below in your config 

"doorCode": "yourcode"

**Comment by bjornand1** [comment]
That did it!
