### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by terjecorneliussen** [ptz0n/homebridge-verisure#21]
When I try to start homebridge I get this back.

[2017-9-20 21:43:21] Loaded plugin: homebridge-philipshue
[2017-9-20 21:43:21] Registering platform 'homebridge-philipshue.PhilipsHue'
[2017-9-20 21:43:21] ---
[2017-9-20 21:43:21] Loaded plugin: homebridge-verisure
[2017-9-20 21:43:21] Registering platform 'homebridge-verisure.verisure'
[2017-9-20 21:43:21] ---
[2017-9-20 21:43:21] There was a problem reading your config.json file.
[2017-9-20 21:43:21] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-9-20 21:43:21] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token } in JSON at position 577
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

My config-file:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform" : "PhilipsHue",
            "name" : "Hue",
            "ip_address": "xx",
            "username": "xxxx"
        }
        {
            "platform" : "verisure",
            "name" : "Verisure",
            "email": "xxx@xxxx.xx",
            "password": "xxxxxxx",
            "doorcode": "xxxxxx"
        }
    ]
}

Without the verisure platform it works perfectly.

Some ideas?

**Comment by wahlly** [comment]
There is a comma missing after the last phillipshue bracket. It should look like this.

`{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",


"platforms": [
    {
        "platform" : "PhilipsHue",
        "name" : "Hue",
        "ip_address": "xx",
        "username": "xxxx"
    },
    {
        "platform" : "verisure",
        "name" : "Verisure",
        "email": "xxx@xxxx.xx",
        "password": "xxxxxxx",
        "doorcode": "xxxxxx"
    }
]
}`

**Comment by terjecorneliussen** [comment]
Thanks a lot! That was easy... Works perfect now!
