### ISSUE TITLE
Cannot read propery giid of undefined

### ISSUE THREAD

**Issue by yabbah** [ptz0n/homebridge-verisure#3]
Got this error when trying to launch homebridge after installed the plugin and edited the config.json.
```
[2017-01-30 12:13:17] [Verisure] Initializing verisure platform...
Load homebridge-verisure.verisure
/usr/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:50
    giid = typeof installation == 'string' ? installation : installation.giid
                                                                        ^

TypeError: Cannot read property 'giid' of undefined
    at Object.overview (/usr/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:50:73)
    at /usr/lib/node_modules/homebridge-verisure/index.js:84:16
    at /usr/lib/node_modules/homebridge-verisure/index.js:31:7
    at Request._callback (/usr/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:45:7)
    at Request.self.callback (/usr/lib/node_modules/homebridge-verisure/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-verisure/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-verisure/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

Here is my config.json:

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "description": "This is an example.",
  "platforms": [
    {
      "platform": "verisure",
      "name": "Verisure",
      "public_key": "XXXXXXXXXXXXXXX",
      "private_key": "XXXXXXXXXXXXXXX",
      "token": "XXXXXXXXXXXXXXX",
      "token_secret": "XXXXXXXXXXXXXXX",
      "email": "XXXXXXXXXXXXXXX",
      "password": "XXXXXXXXXXXXXXX",
      "unknown_accessories": [
        {
          "id": 5338463,
          "model": "test1",
          "manufacturer": "Nexa",
          "name": "test1"
        },
        {
          "id": 8998040,
          "model": "test2",
          "manufacturer": "Oregon",
          "name": "test2"
        }
      ]
    }
  ]
}
```

Any idea?

**Comment by elbogi** [comment]
Hello. Try changing your config.json to look like eg. this: 
`{ "bridge": {
"name": "HomeBridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"description": "HomeBridge HTTP Status Control",
"platforms": [{
    "platform" : "verisure",
    "name" : "Verisure",
    "email": "your@email.here",
    "password": "<insertPassword>"
}]
}`

Give it a try to see if this helps. Your config.json looks strange to me.

**Comment by ptz0n** [comment]
Oh, yes. As @elbogi suggests, it should be a separate object in the list of `platforms` in your config.
