### ISSUE TITLE
Error when initializing unsupported device "HUMIDITY1"

### ISSUE THREAD

**Issue by rlundquist** [ptz0n/homebridge-verisure#4]
I have a humidity sensor and when I try to start Homebridge I get the following error:

[1/30/2017, 1:18:16 PM] Loaded plugin: homebridge-verisure
[1/30/2017, 1:18:16 PM] Registering platform 'homebridge-verisure.verisure'
[1/30/2017, 1:18:16 PM] ---
[1/30/2017, 1:18:16 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/30/2017, 1:18:16 PM] ---
[1/30/2017, 1:18:16 PM] Loading 1 platforms...
[1/30/2017, 1:18:16 PM] [Verisure] Initializing verisure platform...
Load homebridge-verisure.verisure
[1/30/2017, 1:18:18 PM] [Verisure] Initializing platform accessory 'HUMIDITY1 (Vind)'...
[1/30/2017, 1:18:18 PM] [Verisure] Device HUMIDITY1 is not yet supported
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:128
    if (existing.UUID === service.UUID) {
                                 ^

TypeError: Cannot read property 'UUID' of null
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:128:34)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:418:19
    at Array.forEach (native)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:402:14)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:105:9
    at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:59:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)

**Comment by elbogi** [comment]
I guess HUMIDITY1 need to be added as another const. and be handled correctly. On your status page on mypages.verisure.com what type of information does HUMIDITY1 give? 

What you could do to further help the developer is fetching the status of your components by running this [module](https://github.com/ptz0n/node-verisure) and give him the **installation overview**.
**NB! Without disclosing any location or serial number details.**

**Comment by rlundquist** [comment]
Basically it gives me temperature and relative humidity.
Ok sure, I'm gonna try and run that and see if I can help fix the handling of this sensor.

**Comment by rlundquist** [comment]
Do you think this will do?
  ```
climateValues:
   [ { deviceLabel: '2AA5 3E6L',
       deviceArea: 'Vind',
       deviceType: 'HUMIDITY1',
       temperature: 2.3,
       humidity: 71.5,
       time: '2017-02-01T20:41:23.000Z' },
     { deviceLabel: '2ADS VEBB',
       deviceArea: 'Vardagsrum',
       deviceType: 'SMOKE2',
       temperature: 23.1,
       humidity: 37,
       time: '2017-02-01T17:41:44.000Z' },
     { deviceLabel: '2ADS VF3E',
       deviceArea: 'Hall Övervåning',
       deviceType: 'SMOKE2',
       temperature: 22.3,
       humidity: 40,
       time: '2017-02-01T17:54:04.000Z' },
     { deviceLabel: '2S5Q EMKB',
       deviceArea: 'Kök',
       deviceType: 'SIREN1',
       temperature: 22.3,
       time: '2017-02-01T20:35:52.000Z' } ],
```
