### ISSUE TITLE
  return Buffer.from(`CPE/${email}:${password}`, 'ascii').toString('base64')

### ISSUE THREAD

**Issue by christophedelanghe** [ptz0n/homebridge-verisure#6]
```
[Verisure] Initializing verisure platform...
/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:15
  return Buffer.from(`CPE/${email}:${password}`, 'ascii').toString('base64')
                ^

TypeError: ascii is not a function
    at Function.from (native)
    at Function.from (native)
    at buildCredientials (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:15:17)
    at Object.module.exports.auth (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:28:35)
    at getVerisureInstallation (/usr/local/lib/node_modules/homebridge-verisure/index.js:30:12)
    at accessories (/usr/local/lib/node_modules/homebridge-verisure/index.js:87:5)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:351:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:295:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by ptz0n** [comment]
What version of Node are you running?

```
$ node --version
```

**Comment by christophedelanghe** [comment]
v4.3.2

**Comment by ptz0n** [comment]
Can you upgrade to v4.5.x?

**Comment by christophedelanghe** [comment]
I did that ... now I get this error:

TypeError: VERISURE_DEVICE_NAMES.includes is not a function
    at getUniqueName (/usr/local/lib/node_modules/homebridge-verisure/index.js:59:28)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:95:19
    at Array.map (native)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:92:46
    at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:59:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by ptz0n** [comment]
Try the latest LTS 🙈

**Comment by askusbloodfist** [comment]
I have the Exakt same problem. So i wonder whats your setup in order to get this working?

Im using a RP 3 and Have all latest packs on it homebridge was just updated aswell. Node-JR is 4.8 cause anything higher wont work @ all atleast for me.  but like the guy above i have the same problem

Soon as i remove The verisure COnfig from Config.Json everything starts working in the house. 
So what are the dependensys to get this working?

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[7/6/2017, 3:57:42 AM] Loaded plugin: homebridge-telldus
[7/6/2017, 3:57:42 AM] Registering platform 'homebridge-telldus.Telldus'
[7/6/2017, 3:57:42 AM] ---
[7/6/2017, 3:57:42 AM] Loaded plugin: homebridge-verisure
[7/6/2017, 3:57:42 AM] Registering platform 'homebridge-verisure.verisure'
[7/6/2017, 3:57:42 AM] ---
[7/6/2017, 3:57:42 AM] Loaded config.json with 0 accessories and 2 platforms.
[7/6/2017, 3:57:42 AM] ---
[7/6/2017, 3:57:42 AM] Loading 2 platforms...
[7/6/2017, 3:57:42 AM] [Verisure] Initializing verisure platform...
[7/6/2017, 3:57:42 AM] [Telldus Liv!e] Initializing Telldus platform...
[7/6/2017, 3:57:42 AM] [Telldus Liv!e] Loading accessories...
[7/6/2017, 3:57:43 AM] Loading 0 accessories...
Load homebridge-verisure.verisure
[7/6/2017, 3:57:43 AM] [Telldus Liv!e] Logged in with user: jim.....
[7/6/2017, 3:57:43 AM] [Telldus Liv!e] Found 0 sensors in telldus live.
[7/6/2017, 3:57:43 AM] [Telldus Liv!e] Found 13 devices in telldus live.
/usr/local/lib/node_modules/homebridge-verisure/index.js:59
  if(VERISURE_DEVICE_NAMES.includes(name)) {
                           ^

TypeError: VERISURE_DEVICE_NAMES.includes is not a function
    at getUniqueName (/usr/local/lib/node_modules/homebridge-verisure/index.js:59:28)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:95:19
    at Array.map (native)
    at /usr/local/lib/node_modules/homebridge-verisure/index.js:92:46
    at /usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:79:7
    at Request._callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/index.js:27:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-verisure/node_modules/verisure/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by askusbloodfist** [comment]
{
	"bridge": {
		"name": "xxxxxxxxxxxxxxxxx",
		"username": "xxxxxxxxxxxxxxxxx",
		"port": xxxxxxxxxxxxxxxxx,
		"pin": "xxxxxxxxxxxxxx"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [],

	"platforms": [{
			"platform": "Telldus",
			"name": "Telldus Liv!e",
			"public_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"private_key": "xxxxxxxxxxxxxxxxxxx",
			"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"token_secret": "xxxxxxxxxxxxxxxxxxxxxxxxx",
			"unknown_accessories": [{
					"id": 1554085,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554089,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554113,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554140,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554049,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1554060,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 123,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1602418,
					"model": "selflearning-dimmer",
					"manufacturer": "Nexa"
				},
				{
					"id": 1603882,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1603887,
					"model": "selflearning-switch",
					"manufacturer": "Nexa"
				},
				{
					"id": 1666884,
					"model": "selflearning-switch",
					"manufacturer": "Cotech"
				},
				{
					"id": 456,
					"model": "temperaturehumidity",
					"manufacturer": "Oregon",
					"name": "My Custom Name"
				},
				{
					"id": 789,
					"name": "Only name altered"
				},
				{
					"id": 987,
					"disabled": true
				},
				{
					"platform": "verisure",
					"name": "Verisure",
					"email": "xxxxxxxxxxxxxxxx",
					"password": "xxxxxxxxxxx"
				}
			]
		}
	]
}
