### ISSUE TITLE
Setting alarm state to Night crashes Homebridge

### ISSUE THREAD

**Issue by oskarlindell** [ptz0n/homebridge-verisure#85]
I am running Homebridge through HOOBS in a docker container on a Synology.

When using the homebridge-verisure plugin for homebridge, in the Eve Home app there are four alarm states: Stay, Away, Night and Disarm. If selecting the Night state, homebridge crashes with the following output in the terminal:

> [Homebridge] [4/18/2020, 1:00:34 PM] [verisure] info Alarm (ADDRESS): Setting target alarm state to: 2
> [Homebridge] [4/18/2020, 1:00:34 PM] Error: Cannot resolve arm state from unknown input: 2
>     at Alarm.resolveArmState (/hoobs/node_modules/homebridge-verisure/lib/accessories/alarm.js:34:13)
>     at Alarm.setTargetAlarmState (/hoobs/node_modules/homebridge-verisure/lib/accessories/alarm.js:58:21)
>     at Characteristic.SecuritySystemTargetState.emit (events.js:311:20)
>     at Characteristic.SecuritySystemTargetState.Characteristic.setValue (/hoobs/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
>     at Bridge.<anonymous> (/hoobs/node_modules/hap-nodejs/lib/Accessory.js:882:22)
>     at Array.forEach (<anonymous>)
>     at Bridge.Accessory._handleSetCharacteristics (/hoobs/node_modules/hap-nodejs/lib/Accessory.js:822:8)
>     at HAPServer.emit (events.js:311:20)
>     at HAPServer._handleCharacteristics (/hoobs/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
>     at HAPServer.<anonymous> (/hoobs/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
> [Homebridge] [4/18/2020, 1:00:34 PM] Got SIGTERM, shutting down Homebridge...

Would it possible to have the Night alarm state actually activating the Stay state so we can avoid this crash if accidentally clicking "Night"?

/Oskar

**Comment by ptz0n** [comment]
That is strange. There should not be a Night option available for the arm accessory.

Which version of Homebridge & homebridge-verisure are you currently running?

**Comment by oskarlindell** [comment]
I am running Homebridge version 0.4.53 (through Hoobs version 3.1.27).

And version 1.11.0 of homebridge-verisure.

Also, the night option does not show up in Apple's Home app, only in Eve's app. Maybe there is no way of hiding it in the Eve app?

**Comment by ptz0n** [comment]
Oh, you used EVE to set it to Night? We could check before trying to set the state to make sure we don’t crash 👍🏼

**Comment by oskarlindell** [comment]
Great!

**Comment by ZEEN0j** [comment]
Off topic. But any chance of changing the name of home to night? So instead of home, away and off it says night, away and off. My physical button from Verisure shows a moon and a sun where the moon represent the current "home" mode. Having it named night would in this instance make more sense.

**Comment by Tommigun1980** [comment]
> Off topic. But any chance of changing the name of home to night? So instead of home, away and off it says night, away and off. My physical button from Verisure shows a moon and a sun where the moon represent the current "home" mode. Having it named night would in this instance make more sense.

I concur. The current naming is a bit of a brain bender.

**Comment by ptz0n** [comment]
What's the translation in your locale? In Swedish, Verisure refers to this kind of arm state as "Skalskydd" which translates to shell protection/perimeter.

On my panel, there is two illustrations with a person inside a house.

Verisure is obviously not consistent.

![page_5](https://user-images.githubusercontent.com/200250/133211832-44509863-b99a-42ba-b8a6-70c0fcfacd38.jpg)

**Comment by ZEEN0j** [comment]
> What's the translation in your locale? In Swedish, Verisure refers to this kind of arm state as "Skalskydd" which translates to shell protection/perimeter.
> 
> On my panel, there is two illustrations with a person inside a house.
> 
> Verisure is obviously not consistent.
> 
> ![page_5](https://user-images.githubusercontent.com/200250/133211832-44509863-b99a-42ba-b8a6-70c0fcfacd38.jpg)

I can see how the current naming makes sense in the way Verisure labels the states with numbered panel. But I mostly use the “Trygghetspanel” with the moon and sun. In this scenario the naming doesn’t make sense. Maybe change it to home, on and off or night, on and off? I guess the question is should the naming follow Verisure logic or a more generic naming scheme. 

PS. Verisure just announced Arlo video doorbell
